services:
  backend:
    container_name: just-live-backend
    image: ghcr.io/atsushiutsumi/lightsail-test:just-live-backend
    expose:
      - "8000"
    volumes:
      - sqlite_data:/app/db
    environment:
      - DEBUG=${DEBUG:-0}
    restart: unless-stopped

  frontend:
    container_name: just-live-frontend
    image: ghcr.io/atsushiutsumi/lightsail-test:just-live-frontend
    restart: unless-stopped

  nginx:
    container_name: just-live-nginx
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  sqlite_data: