services:
  backend:
    container_name: just-live-backend
    image: ghcr.io/AtsushiUtsumi/lightsail-test:just-live-backend
    expose:
      - "8000"
    volumes:
      - sqlite_data:/app/db
    environment:
      - DEBUG=${DEBUG:-0}
    restart: unless-stopped

  nginx:
    container_name: just-live-nginx
    image: ghcr.io/AtsushiUtsumi/lightsail-test:just-live-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data: